### ISSUE TITLE
python 3.10 support

### ISSUE THREAD

**Issue by lucize** [dtlzp/Domoticz-Dingtian-Relay-Plugin#4]
testing the board Dingtian DT-R008,Hardwore Version V3.6A, Software Version V3.1.276A, with domoticz 2022.1 on python 3.10 and I get this form the plugin 1.3, `Python exception set prior to callback 'onMessage'`
Also it seems no status is reported, or is this expected ?

**Comment by dtlzp** [comment]
we have test 
x86-64 + virtualbox + debian11+domoticz 2021.1+python 3.9.2 is ok
x86-64 + windows 10 +domoticz 2020.02-x86+python 3.8.2-32bit is ok,

but some Raspbian with python 3.9.x is not ok(the python VM crashed),i don't known why.

can you tell me you environment,like hardware,OS,... and exception log

thanks


 
From: Lucian CRISTIAN
Date: 2022-04-01 18:59
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: Subscribed
Subject: [dtlzp/Domoticz-Dingtian-Relay-Plugin] python 3.10 support (Issue #4)
testing the board Dingtian DT-R008,Hardwore Version V3.6A, Software Version V3.1.276A, with domoticz 2022.1 on python 3.10 and I get this form the plugin 1.3, Python exception set prior to callback 'onMessage'
Also it seems no status is reported, or is this expected ?

**Comment by lucize** [comment]
I think this an issue only with python 3.10
I'm testing on openwrt, x86_64 or aarch64

```
libpython3-3.10 - 3.10.4-1
python3 - 3.10.4-1
```
but the main question is that if the board should return status, because I always see the switch as off
if the the board is not setup to send data to domoticz then I don't see the follwing error: `Dingtian-241: Python exception set prior to callback 'onMessage'` and that is the only message I see in the app syslog

**Comment by dtlzp** [comment]
can you change "Debug" to True, then we can get full log,and send full log to me
thanks




 
From: Lucian CRISTIAN
Date: 2022-04-01 22:57
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: lzp; Comment
Subject: Re: [dtlzp/Domoticz-Dingtian-Relay-Plugin] python 3.10 support (Issue #4)
I think this an issue only with python 3.10
I'm testing on openwrt, x86_64 or aarch64
libpython3-3.10 - 3.10.4-1
python3 - 3.10.4-1

but the main question is that if the board should return status, because I always see the switch as off
if the the board is not setup to send data to domoticz then I don't see the follwing error: Dingtian-241: Python exception set prior to callback 'onMessage' and that is the only message I see in the app syslog

**Comment by lucize** [comment]
sadly no detailed debug is available with this set to true, only what domoticz is sending to the relay.
I also tested with stable branch OpenWrt 21.02.2 that has python 3.9.11 and it seems that I get the status of the relay, so this means that something has changed with python 3.10, I guess I can use the stable branch for testing and maybe you'll have the time to investigate python 3.10 later

**Comment by dtlzp** [comment]
ok,i will test it with python 3.10.x
when i have new idea, i will info you
thanks



 
From: Lucian CRISTIAN
Date: 2022-04-02 18:41
To: dtlzp/Domoticz-Dingtian-Relay-Plugin
CC: lzp; Comment
Subject: Re: [dtlzp/Domoticz-Dingtian-Relay-Plugin] python 3.10 support (Issue #4)
sadly no detailed debug is available with this set to true, only what domoticz is sending to the relay.
I also tested with stable branch OpenWrt 21.02.2 that has python 3.9.11 and it seems that I get the status of the relay, so this means that something has changed with python 3.10, I guess I can use the stable branch for testing and maybe you'll have the time to investigate python 3.10 later
